---
- import_tasks: check_system.yml

- name: Change max_map_count value of sysctl
  sysctl:
    name: vm.max_map_count
    value: 262144

- name: Make a data directory to be mounted and grant access permissions
  shell: |
    mkdir -p /usr/share/elasticsearch/data
    chmod g+rwx /usr/share/elasticsearch/data
#    chgrp 0 /usr/share/elasticsearch/data

- name: 'Run elasticsearch docker container version {{ version }}'
  docker_container:
    name: elasticsearch
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:{{ version }}'
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
    env:
      cluster.name: '{{ cluster.name }}'
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms1g -Xmx1g'
    log_driver: syslog
    ulimits:
      - memlock:-1:-1
      - nofile:65536:65536
    recreate: yes
    restart_policy: unless-stopped
